### ISSUE TITLE
clustering.properties no longer read on each boot of Jamf Pro

### ISSUE THREAD

**Issue by pboushy** [jamf/jamfpro#22] opened 2023-01-20 21:54 UTC
It appears that at least in Jamf Pro 10.42.1 the `clustering.properties` file used in [this portion of the code](https://github.com/jamf/jamfpro/blob/5096c032e31ca710660872831d6327b7153a75bc/configuration.sh#L147-L154) is no longer read on each boot.

I've spent the past few weeks with Jamf Support working on this as part of CS0898484.
I've asked for details on if this was on purpose, or accidental and will be fixed.

Figured the maintainers of this repo would like to know about it since this is where I first found out about that file.

If y'all find anything out I would love to get an update, so far the answer is "this isn't really supported"

**Comment by battlecow** [comment] 2023-01-21 02:37
In my (albeit brief) testing on 10.42.1, the file still works as intended and does indeed automate the setting of the primary node on startup and moves of the primary. Depending on how your environment is setup in Kubernetes however you may need to update which ip is being passed as the `POD_IP`. This ip needs to be the ip from the perspective of the mysql server, so if deploying in cluster the pod ip would work whereas if deployed outside of the cluster, the actual external node ip would have to be passed into the deployment/pod config.

**Comment by pboushy** [comment] 2023-01-21 03:48
I pass hostIP as POD_IP. I’ve been running this for well over a year with a variety of versions, and they all worked till this attempt to upgrade.

The setup where I experienced it is my pre-prod environment. I haven’t attempted reproducing with fewer variables but I’ll see what I can do.

Here are the steps I plan on doing to attempt to reproduce
1. Deploy docker image, and memcached. Make sure the proper ENV variables are set so that it enables memcached, and clustering.
2. Complete setup of Jamf Pro, confirm clustering is enabled, shows correct IP, and shows memcached.
4. Shutdown docker image.
5. Redeploy docker image ensuring that the IP that DB sees it from is different, and check if it boots properly. In my env memcached failed to be configured because new pod wasn’t the “primary” even though clustering.properties said it was.

**Comment by battlecow** [comment] 2023-02-11 20:37
Just wanting to check in and see if you were able to reproduce the issue?

**Comment by battlecow** [comment] 2023-03-18 19:55
Hey there, it's been awhile since this issue was opened and responded to so I am going to close it, but please do feel free to open a new case if you are able to reproduce the issue.

**Closed as completed by battlecow** 2023-03-18 19:55 UTC
